services:
  payment_orders_db:
    image: postgres
    environment:
      POSTGRES_DB: payment_orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  

  payment_order_app:
    image: payment-orders-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment_orders_db:5432/payment_orders_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Passw0rd
    ports:
      - "8080:8080"
    depends_on: 
      payment_orders_db:
        condition: service_healthy